import { readFile, writeFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import { pathToFileURL } from 'node:url'

type MessageDescriptor = {
  message: string
}

const canonicalCatalogPath = resolve(
  'public',
  '_locales',
  'en',
  'messages.json'
)
const generatedKeysPath = resolve('src', 'i18n', 'message-keys.generated.ts')

export const collectMessageKeys = (catalog: unknown): string[] => {
  if (!catalog || typeof catalog !== 'object' || Array.isArray(catalog)) {
    throw new TypeError('The canonical message catalog must be an object.')
  }

  const entries = Object.entries(catalog)
  for (const [key, descriptor] of entries) {
    const message = (descriptor as Partial<MessageDescriptor> | null)?.message

    if (typeof message !== 'string' || message.trim().length === 0) {
      throw new TypeError(`Message "${key}" must contain non-empty text.`)
    }
  }

  return entries.map(([key]) => key).sort()
}

export const renderMessageKeys = (keys: readonly string[]): string => {
  const members = keys.map(key => `  ${JSON.stringify(key)},`).join('\n')

  return `// Generated by src/i18n/generate-message-keys.ts. Do not edit.
export const messageKeys = [
${members}
] as const;

export type MessageKey = (typeof messageKeys)[number];
`
}

export const generateMessageKeys = async (
  checkOnly: boolean
): Promise<void> => {
  const catalog = JSON.parse(
    await readFile(canonicalCatalogPath, 'utf8')
  ) as unknown
  const expected = renderMessageKeys(collectMessageKeys(catalog))

  if (checkOnly) {
    const current = await readFile(generatedKeysPath, 'utf8').catch(() => '')
    if (current !== expected) {
      throw new Error(
        'Generated message keys are stale. Run `pnpm i18n:generate`.'
      )
    }
    return
  }

  await writeFile(generatedKeysPath, expected, 'utf8')
}

const entrypoint = process.argv[1]
if (entrypoint && import.meta.url === pathToFileURL(resolve(entrypoint)).href) {
  await generateMessageKeys(process.argv.includes('--check'))
}
