import { t } from '@/i18n/runtime'

export const getRuleWorkbenchCopy = () => ({
  advancedRuleLabel: t('rulesAdvancedRuleLabel'),
  allowDescription: t('rulesAllowDescription'),
  allowLabel: t('rulesAllowLabel'),
  backAction: t('rulesBackAction'),
  blockDescription: t('rulesBlockDescription'),
  blockLabel: t('rulesBlockLabel'),
  cancelAction: t('rulesCancelAction'),
  createAction: t('rulesCreateAction'),
  dataAction: t('rulesDataAction'),
  editAction: t('rulesEditAction'),
  editorDescription: t('rulesEditorDescription'),
  editorEffectLabel: t('rulesEditorEffectLabel'),
  editorEyebrow: t('rulesEditorEyebrow'),
  editorNewTitle: t('rulesEditorNewTitle'),
  editorUpdateTitle: t('rulesEditorUpdateTitle'),
  failureBody: t('rulesFailureBody'),
  failureTitle: t('rulesFailureTitle'),
  hideLabel: t('rulesHideLabel'),
  listDescription: t('rulesListDescription'),
  listEyebrow: t('rulesListEyebrow'),
  listTitle: t('rulesListTitle'),
  newAction: t('rulesNewAction'),
  pendingAction: t('rulesPendingAction'),
  pendingBody: t('rulesPendingBody'),
  pendingTitle: t('rulesPendingTitle'),
  phraseError: t('rulesPhraseError'),
  phraseHint: t('rulesPhraseHint'),
  phraseLabel: t('rulesPhraseLabel'),
  previewAction: t('rulesPreviewAction'),
  previewDescription: t('rulesPreviewDescription'),
  previewEyebrow: t('rulesPreviewEyebrow'),
  previewMatchLabel: t('rulesPreviewMatchLabel'),
  previewProtectedLabel: t('rulesPreviewProtectedLabel'),
  previewProtectedItemTitle: t('rulesPreviewProtectedItemTitle'),
  previewTitle: t('rulesPreviewTitle'),
  privacyBadge: t('panelPrivacyBadge'),
  privacyDescription: t('panelPrivacyDescription'),
  privacyTitle: t('panelPrivacyTitle'),
  ruleScope: t('rulesRuleScope'),
  saveAction: t('rulesSaveAction'),
  savedBody: t('rulesSavedBody'),
  savedTitle: t('rulesSavedTitle'),
  savingAction: t('rulesSavingAction'),
  showLabel: t('rulesShowLabel'),
  unchangedLabel: t('rulesUnchangedLabel'),
  undoAction: t('rulesUndoAction'),
  undoneBody: t('rulesUndoneBody'),
  undoneTitle: t('rulesUndoneTitle')
})

export type RuleWorkbenchCopy = ReturnType<typeof getRuleWorkbenchCopy>
